<?php
function block_morelink_form_block_admin_configure_alter(&$form, &$form_state) {
	$result = db_query ( "SELECT url, title FROM {block_morelink} WHERE module = :module AND delta = :delta", array (
			':module' => $form ['module'] ['#value'],
			':delta' => $form ['delta'] ['#value'] 
	) )->fetch ();
	$default_morelink_url = empty ( $result ) ? '' : $result->url;
	$default_morelink_title = empty ( $result ) ? '' : $result->title;
	$form ['settings'] ['morelink_url'] = array (
			'#type' => 'textfield',
			'#title' => t ( 'More Link url' ),
			'#maxlength' => 255,
			'#description' => t ( 'The More Link url of the block as shown to the user.' ),
			'#default_value' => $default_morelink_url,
			'#weight' => - 17 
	);
	$form ['settings'] ['morelink_title'] = array (
			'#type' => 'textfield',
			'#title' => t ( 'More Link title' ),
			'#maxlength' => 255,
			'#description' => t ( 'The More Link title of the block as shown to the user.' ),
			'#default_value' => $default_morelink_title,
			'#weight' => - 17 
	);
	$form ['#validate'] [] = 'block_morelink_block_admin_configure_validate';
	$form ['#submit'] [] = 'block_morelink_block_admin_configure_submit';
}
function block_morelink_form_block_add_block_form_alter(&$form, &$form_state) {
	block_morelink_form_block_admin_configure_alter ( $form, $form_state );
}

/**
 * Form validate handler for block configuration form.
 */
function block_morelink_block_admin_configure_validate($form, &$form_state) {
	// Todo
}
function block_morelink_block_admin_configure_submit($form, &$form_state) {
	db_delete ( 'block_morelink' )->condition ( 'module', $form_state ['values'] ['module'] )->condition ( 'delta', $form_state ['values'] ['delta'] )->execute ();
	
	if (! empty ( $form_state ['values'] ['morelink_url'] )) {
		$query = db_insert ( 'block_morelink' )->fields ( array (
				'url',
				'title',
				'module',
				'delta' 
		) );
		$query->values ( array (
				'url' => $form_state ['values'] ['morelink_url'],
				'title' => $form_state ['values'] ['morelink_title'],
				'module' => $form_state ['values'] ['module'],
				'delta' => $form_state ['values'] ['delta'] 
		) );
		$query->execute ();
	}
}
function block_morelink_preprocess_block(&$variables) {
	$result = db_query ( "SELECT url, title FROM {block_morelink} WHERE module = :module AND delta = :delta", array (
			':module' => $variables ['block']->module,
			':delta' => $variables ['block']->delta 
	) )->fetch ();
	$morelink_url = empty ( $result ) ? '' : $result->url;
	$morelink_title = empty ( $result ) ? '' : $result->title;
	if ($morelink_url != '') {
		// $variables ['block']->morelink = '<span class="block-more-link">' . l ( t ( 'More' ), $morelink_url, array (
		// 'attributes' => array (
		// 'title' => $morelink_title
		// )
		// ) ) . '</span>';
		if ($morelink_url != '') {
			$variables ['block']->morelink = theme ( 'block_morelink_link', array (
					'url' => $morelink_url,
					'title' => $morelink_title 
			) );
		}
	}
}
function block_morelink_theme() {
	return array (
			'block_morelink_link' => array (
					'variables' => array (
							'url' => NULL,
							'title' => NULL 
					) 
			) 
	);
}
function theme_block_morelink_link($variables) {
	$output = "";
	if (! empty ( $variables ['url'] )) {
		$morelink_label = t ( 'More' );
		$output .= '<span class="block-more-link">' . l ( $morelink_label, $variables ['url'], array (
				'attributes' => array (
						'title' => $variables ['title'] 
				) 
		) ) . '</span>';
	}
	return $output;
}
function block_morelink_menu() {
	// Block settings.
	$items ['admin/config/block'] = array (
			'title' => 'Block',
			'description' => 'Block configuration.',
			'position' => 'left',
			'weight' => - 10,
			'page callback' => 'system_admin_menu_block_page',
			'access arguments' => array (
					'access administration pages' 
			),
			'file' => 'system.admin.inc',
			'file path' => drupal_get_path ( 'module', 'system' ) 
	);
	$items ['admin/config/block/morelink'] = array (
			//'title' => 'More link',
			'title' => 'More link',
			'description' => 'the more link lable of block.',
			'page callback' => 'drupal_get_form',
			'page arguments' => array (
					'block_morelink_label_settings' 
			),
			'access arguments' => array (
					'administer site configuration' 
			),
			'weight' => - 10,
			'file' => 'block_morelink.admin.inc' 
	);
	return $items;
}