<?php
function milkshake_menu() {
	$items ['milkshake'] = array (
			'title' => 'Milkshake flavors',
			'access callback' => true,
			'page callback' => 'milkshake_overview',
			'type' => MENU_NORMAL_ITEM 
	);
	
	$items ['milkshake/list'] = array (
			'title' => 'List flavors',
			'access callback' => TRUE,
			'type' => MENU_DEFAULT_LOCAL_TASK,
			'weight' => 0 
	);
	$items ['milkshake/add'] = array (
			'title' => 'Add flavor',
			'access callback' => TRUE,
			'page callback' => 'milkshake_add',
			'type' => MENU_LOCAL_TASK,
			'weight' => 1 
	);
	$items ['milkshake/list/fruity'] = array (
			'title' => 'Fruity flavors',
			'access callback' => TRUE,
			'page callback' => 'milkshake_list',
			'page arguments' => array (
					2 
			), // pass 'fruity'.
			'type' => MENU_LOCAL_TASK 
	);
	$items ['milkshake/list/candy'] = array (
			'title' => 'Candy flavors',
			'access callback' => TRUE,
			'page callback' => 'milkshake_list',
			'page arguments' => array (
					3 
			), // pass 'Candy'.
			'type' => MENU_LOCAL_TASK 
	);
	
	return $items;
}
function milkshake_overview() {
	$output = t ( 'The following flavors are available...' );
	return $output;
}
function milkshake_add() {
	return t ( 'A handy form to add flavors might go here...' );
}
function milkshake_list($type) {
	return t ( 'List @type flavors', array (
			'@type' => $type 
	) );
}