<?php
function job_post_node_info() {
	return array (
			'job_post' => array (
					'name' => t ( 'Job Post' ),
					'base' => 'job_post',
					'description' => t ( 'Use this content type to post a job.' ),
					'has_title' => TRUE,
					'title_label' => t ( 'Job Title' ),
					'help' => t ( 'Enter the job title,
                    job description, and the name of the company that posted the job' ) 
			) 
	);
}
function job_post_help($path, $args) {
	$filename = 'logxxx.txt';
	// file_put_contents ( 'logxxx.txt', $path );
	//file_put_contents ( $filename, file_get_contents ( $filename ) . "\r\n" . $path );
	switch ($path) {
		case 'admin/help#job_post' :
			return load_node_info ();
			break;
		default :
			return '';
			break;
	}
}
function load_node_info() {
	$types = node_type_get_types ();
	return json_encode ( $types );
}
function job_post_form($node, $form_state) {
	return node_content_form ( $node, $form_state );
}